# Generated by Django 4.2.6 on 2023-10-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gadgets', '0002_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='for_user',
            field=models.CharField(default='Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos iusto qui aliquam ea corrupti? Libero quod, magnam illo ut nostrum cumque ex vitae esse eligendi vel ullam consequatur nobis accusamus!', max_length=300),
        ),
        migrations.AddField(
            model_name='item',
            name='prod_code',
            field=models.IntegerField(default=100),
        ),
    ]
