# Generated by Django 4.2.6 on 2023-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gadgets', '0006_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
    ]
