# Generated by Django 4.2.6 on 2023-11-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gadgets', '0007_alter_history_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('KB', 'Keyboard'), ('MO', 'Mouse'), ('HP', 'Headphone'), ('CS', 'Computer Specs')], max_length=2, null=True),
        ),
    ]
